apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-slack
  namespace: backend-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: backend-slack
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: backend/prod/slack