apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-prod

resources:
  - namespace.yaml
  - configmap-backend.yaml
  - external-secrets.yaml
  - ../../base

patches:
  - target:
      kind: Ingress
      name: backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: application-prod.local

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_ME_BACKEND_IMAGE_PROD